name: Makefile CI

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.7 
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.7'
        architecture: 'x64'

    - name: Install dependencies
      run: make install

    - name: lint
      run: make lint

    - name: Run check
      run: make test
